# Generated by Django 4.2.5 on 2024-09-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_firewall", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fwstaff",
            name="ip_version",
            field=models.CharField(
                choices=[("inet", "Ipv4"), ("inet6", "Ipv6")],
                default="inet",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="fwregions",
            name="device_type",
            field=models.CharField(
                choices=[("Arista", "Arista"), ("OPNsense", "Opnsense")], max_length=50
            ),
        ),
    ]
