# Generated by Django 4.2.5 on 2024-06-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_firewall", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fwstaff",
            name="port",
        ),
        migrations.AddField(
            model_name="fwstaff",
            name="dst_port",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fwstaff",
            name="src_port",
            field=models.IntegerField(default=0),
        ),
    ]
