# Generated by Django 4.2.5 on 2024-07-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_firewall", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fwstaff",
            name="instance_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
