# Generated by Django 4.2.5 on 2024-06-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff_firewall", "0002_remove_fwstaff_port_fwstaff_dst_port_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fwstaff",
            old_name="regions",
            new_name="region",
        ),
    ]
