# Generated by Django 4.2.5 on 2024-06-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_firewall", "0003_rename_regions_fwstaff_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="fwstaff",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fwstaff",
            name="ip",
            field=models.GenericIPAddressField(),
        ),
    ]
