# Generated by Django 4.2.5 on 2024-07-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_firewall", "0004_alter_fwstaff_instance_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fwstaff",
            name="instance_id",
            field=models.UUIDField(null=True),
        ),
    ]
