# Generated by Django 4.2.5 on 2024-06-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_firewall", "0004_fwstaff_description_alter_fwstaff_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="fwstaff",
            name="firewall_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
