# Generated by Django 4.2.5 on 2024-06-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_firewall", "0005_fwstaff_firewall_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fwstaff",
            name="dst_port",
        ),
        migrations.RemoveField(
            model_name="fwstaff",
            name="ip",
        ),
        migrations.RemoveField(
            model_name="fwstaff",
            name="src_port",
        ),
        migrations.AddField(
            model_name="fwstaff",
            name="destination_ip",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name="fwstaff",
            name="destination_port",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="fwstaff",
            name="direction",
            field=models.CharField(
                choices=[("in", "Input"), ("OUT", "Output")],
                default="in",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="fwstaff",
            name="interface",
            field=models.CharField(
                choices=[("opt1", "Public Net V4 V6"), ("None", "Public Net V6 Only")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fwstaff",
            name="protocol",
            field=models.CharField(
                choices=[("any", "Any"), ("tcp", "Tcp"), ("udp", "Udp")],
                default="any",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="fwstaff",
            name="source_ip",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name="fwstaff",
            name="source_port",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="fwregions",
            name="device_type",
            field=models.CharField(
                choices=[("Arista", "Arista"), ("OPNsence", "Opnsence")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="fwstaff",
            name="action",
            field=models.CharField(
                choices=[("pass", "Allow"), ("block", "Block")],
                default="block",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="FwActions",
        ),
        migrations.DeleteModel(
            name="FwDeviceType",
        ),
    ]
