# Generated by Django 4.2.5 on 2024-06-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "staff_firewall",
            "0007_alter_fwregions_device_type_alter_fwstaff_direction_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fwstaff",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
    ]
