# Generated by Django 4.2.5 on 2024-06-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "staff_firewall",
            "0012_alter_fwregions_api_key_alter_fwregions_api_secret_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fwregions",
            name="api_secret",
            field=models.BinaryField(editable=True),
        ),
    ]
