# Generated by Django 4.2.5 on 2024-06-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff_firewall", "0014_alter_fwregions_api_key_alter_fwregions_api_secret"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fwregions",
            old_name="api_key",
            new_name="api_key_encrypted",
        ),
        migrations.RenameField(
            model_name="fwregions",
            old_name="api_secret",
            new_name="api_secret_encrypted",
        ),
    ]
